"""Pandas101.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PQcY7wh17ajxTCOPaj9bKft4gASyOE2N
"""

url = 'https://raw.github.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/tips.csv'

import pandas as pd

datos = pd.read_csv(url)
print(datos)

datos['tip']

datos['smoker']

"""Mostrar solo 4 columnas: 'total_bill', 'tip', 'smoker', 'time'"""

columnas = ['total_bill','tip','smoker','time']
datos[columnas]

datos[['total_bill','tip','smoker','time']]

"""Mostrar solo 2 columnas: 'total_bill' y 'day'"""

columnas = ["total_bill", "day"]
datos[columnas]

datos[['total_bill', 'day']]

"""Mostrar las 7 columnas y solo los primeros 5 registros"""

datos.head(5)

n_registros = 5
datos2 = datos.head(n_registros)
print(datos2)

"""Mostrar las 3 columnas: 'tip', 'sex' y 'size' con solo los 10 primeros registros"""

print(datos[['tip', 'sex', 'size']].head(10))

n_registros = 10
datos2 = datos.head(n_registros)[["tip","sex","size"]]
print(datos2)

datos[['tip', 'sex', 'size']].head(10)

"""Valor booleanos (bits): 

1 es True
0 es False
"""

print(datos)

datos['size']==3

booleanos = (datos['size']==3)

booleanos

"""Mostrar todos los registros donde size=3"""

print(datos[booleanos])

""" Mostrar todos los registros donde time='Dinner'"""

din = (datos["time"]=="Dinner")
print(datos[din])

"""Mostrar todos los registros donde 'sex'='Female' y 'day'='Sun'"""

booleanos = (datos['sex']=='Female') & (datos['day']=='Sun')
print(booleanos)

print(datos[booleanos])

"""Mostrar todos los registros donde 'sex'='Male' y 'day'='Fri' y 'Smoker'='No'"""

s=((datos['sex']=="Male") & (datos['day']=="Fri") & (datos['smoker']=="No"))
print(datos[s])

booleanos = (datos["sex"]=="Male") & (datos["day"]=="Fri") & (datos["smoker"]=="No")
print(datos[booleanos])

sds = (datos['sex'] == 'Male') & (datos['day'] == 'Fri') & (datos['smoker'] == 'No')
datos[sds]

"""Mostrar los registros donde el día es jueves o viernes: day='Fri' o day='Thur'"""

sds = (datos['day'] == 'Fri') | (datos['day'] == 'Thur')
datos[sds]

states = ((datos["day"]=="Fri") | (datos["day"] == "Thur"))

print(datos[states])

s = ((datos["day"]) == "Fri") | ((datos["day"]) == "Thur")
print(datos[s])

filt = (datos['day'] == 'Fri') | (datos['day'] == 'Thur')
print(datos[filt])

"""Mostrar los priemros 8 registros donde 'sex'='Male' y 'day'='Fri' o 'day'='Thur' y 'Smoker'='Yes'"""

male = (datos["sex"]=="Male")
day = (datos["day"]=="Fri") | (datos["day"]=="Thur")
smoker = (datos["smoker"]=="Yes")
booleanos = male & day & smoker
print(datos[booleanos].head(8))

b = (datos['sex']=='Male') & ((datos['day']=='Fri') | (datos['day']=='Thur')) & (datos['smoker']=='Yes')
print (datos[b].head(8))

"""Mostrar la cantidad de personas que son fumadores"""

fumadores = (datos['smoker'] == 'Yes')
print(fumadores)

conteos = fumadores.value_counts()
print(conteos)

print("La cantidad de fumadores es {}".format(conteos[1]))

print("La cantidad de NO fumadores es {}".format(conteos[0]))

"""Mostrar la cantidad de registros donde las personas son fumadoras y el día es domingo"""

booleanos = (datos["smoker"]=="Yes") & (datos["day"]=="Sun")
conteo = booleanos.value_counts()
print(conteo)

print("Hay {} registros donde las personas son fumadoras y el día es domingo".format(conteo[1]))

"""Mostrar los primeros 10 registros donde sea cena y la propina sea mayor que 5.00"""

booleanos = ((datos['tip']>5.00) & (datos['time']=='Dinner'))
print(datos[booleanos].head(10))
